config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :cart_items
  resources :addresses

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
    resources :product_lists
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  namespace :admin do
    resources :orders do
      member do
        post :ship
        post :deliver
        post :return_good
        post :cancel
      end
    end
    resources :products do
      get :publish
      get :unpublish
    end
  end

  namespace :account do
    resources :orders
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  before_create :generate_token
  belongs_to :address
  has_many :product_lists
  include AASM

  aasm do
    state :order_placed, initial: true #默认状态“已下单”
    state :paid                        #已付款
    state :shipping                    #已发货，运送中…
    state :shipped                     #已收获
    state :order_cancelled             #取消订单
    state :good_returned               #退货

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid ,        to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

  def generate_token
    self.token = SecureRandom.uuid
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  def set_payment_method!(method)
    self.update(payment_method: method)
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order("id DESC")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
    @user = @order.user
    @product_lists = @order.product_lists
  end

  def ship
    @order = Order.find params[:id]
    @order.ship!
    OrderMailer.notify_ship(@order).deliver!
    redirect_back(fallback_location: root_path)
  end

  def deliver
    @order = Order.find params[:id]
    @order.deliver!
    redirect_back(fallback_location: root_path)
  end

  def return_good
    @order = Order.find params[:id]
    @order.return_good!
    redirect_back(fallback_location: root_path)
  end

  def cancel
    @order = Order.find params[:id]
    @order.cancel_order!
    OrderMailer.notify_cancel(@order).deliver!
    flash[:alert] = "订单已取消"
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only:[:create, :show]

  def create
    @address = Address.find params[:address_id]
    order = Order.new order_params
    order.address_id = @address.id
    order.user_id = current_user.id
    if order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order_id = order.id
        product_list.picture = cart_item.product.avatar.mini.url
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.product_quantity = cart_item.quantity
        product_list.save
      end
      OrderMailer.notify_order_placed(order).deliver!
      redirect_to order_path(order.token)
      flash[:notice] = "已生成订单！"
    end
  end

  def show
    @order = Order.find_by(token: params[:id])
  end

  def pay_with_wechat
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("微信")
    @order.make_payment!
    flash[:notice] = "用微信支付成功"
    redirect_to account_orders_path
  end

  def pay_with_alipay
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("支付宝宝")
    @order.make_payment!
    flash[:notice] = "用支付宝支付成功"
    redirect_to account_orders_path
  end

  def apply_to_cancel
    @order = Order.find params[:id]
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_back(fallback_location: root_path)
  end

  private
  def order_params
    params.require(:order).permit(:total_money)
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def render_order_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order_aasm_state.html.erb
<% case order.aasm_state %>
<% when "order_placed" %>
<%= link_to "取消订单", cancel_admin_order_path(order), method: :post, class:"btn btn-sm btn-danger pull-right" %>
<% when "paid" %>
<%= link_to "取消订单", cancel_admin_order_path(order), method: :post, class:"btn btn-sm btn-danger pull-right" %>
<%= link_to "设定为出货", ship_admin_order_path(order), method: :post, class:"btn btn-sm btn-success pull-right" %>
<% when "shipping" %>
<%= link_to "送达", deliver_admin_order_path(order), method: :post, class:"btn btn-sm btn-danger pull-right" %>
<% when "shipped" %>
<%= link_to "退货", return_good_admin_order_path(order), method: :post, class:"btn btn-sm btn-danger pull-right" %>
<% when "order_cancelled" %>
<span class="text-muted pull-right">订单已取消</span>
<% when "good_returned" %>
<span class="text-muted pull-right">已退货</span>
<% end %>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h3>所有订单</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>序号</th>
          <th>生成时间</th>
          <th>买家</th>
          <th>订单状态</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= link_to(order.id, admin_order_path(order)) %></td>
          <td><%= order.created_at.to_s(:long) %></td>
          <td><%= order.user.email %></td>
          <td><%= order.aasm_state %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4><%= @user.email %>的订单明细（<%= render_order_state(@order) %>）</h4>
    <span>下单时间：<%= @order.created_at.to_s(:long) %></span>
    <%= render "order_aasm_state", order: @order %>

    <table class="table">
      <thead>
        <tr>
          <th>商品信息</th>
          <th>价格</th>
          <th>数量</th>
          <th>小计</th>
        </tr>
      </thead>
      <tbody>
        <% @product_lists.each do |product_list| %>
        <tr>
          <td><%= product_list.product_name %></td>
          <td><%= product_list.product_price %></td>
          <td><%= product_list.product_quantity %></td>
          <td><%= product_list.product_price * product_list.product_quantity %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>