config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :cart_items
  resources :addresses

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
    resources :product_lists
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  namespace :admin do
    resources :orders do
      member do
        post :ship
        post :deliver
        post :return_good
        post :cancel
      end
    end
    resources :products do
      get :publish
      get :unpublish
    end
  end

  namespace :account do
    resources :orders
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.product.price * cart_item.quantity
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  before_create :generate_token
  belongs_to :address
  has_many :product_lists
  include AASM

  aasm do
    state :order_placed, initial: true #默认状态“已下单”
    state :paid                        #已付款
    state :shipping                    #已发货，运送中…
    state :shipped                     #已收获
    state :order_cancelled             #取消订单
    state :good_returned               #退货

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid ,        to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

  def generate_token
    self.token = SecureRandom.uuid
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  def set_payment_method!(method)
    self.update(payment_method: method)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    user_id = current_user.id
    @address = Address.new address_params
    @address.user_id = user_id
    if @address.save
      redirect_to addresses_path
    else
      render :new
    end
  end

  def edit
    @address = Address.find params[:id]
  end

  def update
    @address = Address.find params[:id]
    if @address.update address_params
      redirect_to addresses_path
    else
      render :edit
    end
  end

  private
  def address_params
    params.require(:address).permit(:phone, :shipping_name, :shipping_address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_cart

  def require_admin
    if !current_user.is_admin
      flash.alert = "sorry~~您没有权限"
      redirect_back(fallback_location: root_path)
    end
  end

  def current_cart
    @current_cart ||= find_cart
  end

  private
  def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def edit
  end

  def update
    cart_item = CartItem.find params[:id]
    quantity = params[:cart_item][:quantity]
    if quantity.to_i <= cart_item.product.repertory.to_i
      cart_item.update cart_item_params
    else
      flash[:alert] = "库存不足，所购商品数量不能超过#{cart_item.product.repertory}"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    cart_item = CartItem.find params[:id]
    cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def checkout
    @order = Order.new
    @addresses = current_user.addresses
  end

  def destroy
    current_cart.cart_items.delete_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only:[:create, :show]

  def create
    @address = Address.find params[:address_id]
    order = Order.new order_params
    order.address_id = @address.id
    order.user_id = current_user.id
    if order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order_id = order.id
        product_list.picture = cart_item.product.avatar.mini.url
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.product_quantity = cart_item.quantity
        product_list.save
      end
      OrderMailer.notify_order_placed(order).deliver!
      redirect_to order_path(order.token)
      flash[:notice] = "已生成订单！"
    end
  end

  def show
    @order = Order.find_by(token: params[:id])
  end

  def pay_with_wechat
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("微信")
    @order.make_payment!
    flash[:notice] = "用微信支付成功"
    redirect_to account_orders_path
  end

  def pay_with_alipay
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("支付宝宝")
    @order.make_payment!
    flash[:notice] = "用支付宝支付成功"
    redirect_to account_orders_path
  end

  def apply_to_cancel
    @order = Order.find params[:id]
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_back(fallback_location: root_path)
  end

  private
  def order_params
    params.require(:order).permit(:total_money)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where(publish: true)
  end

  def show
    @product = Product.find params[:id]
  end

  def add_to_cart
    @product = Product.find params[:id]
    if current_cart.products.include?(@product)
      flash[:warning] = "该商品已加入到购物车,不能重复加入"
      redirect_back(fallback_location: root_path)
    else
      current_cart.add_product_to_cart(@product)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def render_order_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def product_quantity(product)
    current_cart.cart_items.find_by(product_id: product.id).quantity
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { notice: "success", warning: "warning", alert: "danger" }.freeze

  def user_facing_flashes
    flash.to_hash.slice "alert", "warning", "notice"
  end

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/checkout.html.erb
<div class="container">
  <div class="row">
    <% total = 0 %>
    <%= simple_form_for @order do |f| %>
    <p>收获地址</p>
    <div class="checkout-addresses">
      <select class="address-single form-control" name="address_id">
        <% @addresses.each do |address| %>
          <option value=<%= address.id %>>
            <%= address.shipping_name %>
            <span>|</span>
            <%= address.phone %>
            <span>|</span>
            <%= address.shipping_address %>
          </option>
        <% end %>
      </select>
    </div>
    <br>
    <!-- <hr> -->
    <table class="cart-product-list table">
      <thead>
        <tr>
          <th>商品信息</th>
          <th>单价</th>
          <th>数量</th>
          <th>小计</th>
          <th>实付</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.products.each do |product| %>
          <tr>
            <td><%= image_tag product.avatar.least.url.to_s %>
              <%= product.title %></td>
            <td>￥<%= product.price.to_i %></td>
            <td><%= product_quantity(product) %></td>
            <td>￥<%= product.price.to_i * product_quantity(product) %></td>
            <td>￥<%= product.price.to_i * product_quantity(product) %></td>
          </tr>
          <% total += product.price.to_i * product_quantity(product) %>
        <% end %>
      </tbody>
    </table>
    <hr>
    <div class="pull-right">
      <p>应付总额: <%= total %>元</p>
      <%= f.hidden_field :total_money, value:"#{ total }" %>
      <%= f.submit "生成订单", class:"btn btn-danger" %>
    </div>
  <% end %>
</div>
</div>
<script type="text/javascript">
$(document).ready(function () {
  $('.address-single').select2();
});
</script>

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>商品信息</th>
          <th>单价</th>
          <th>数量</th>
          <th>小计</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item|  %>
          <tr>
            <td>
              <%= link_to product_path(cart_item.product) do %>
              <%= image_tag cart_item.product.avatar.mini.url %>
              <% end %>
              <%= cart_item.product.title %>
            </td>
            <td>
              ￥
              <%= cart_item.product.price %>
            </td>
            <td>
              <%= form_for cart_item do |f| %>
              <%= f.select :quantity, 1..cart_item.product.repertory %>
              <%= f.submit "更新" %>
              <% end %>
            </td>
            <td>
              ￥
              <%= cart_item.quantity * cart_item.product.price %>
            </td>
            <td>
              <%= link_to "移入收藏夹" %><br>
              <%= link_to "删除", cart_item_path(cart_item.id), method: :delete %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <hr>
    <div class="row">
      <%= link_to "一键清空", cart_path(current_cart), method: :delete, class:"btn btn-danger" %>
      <div class="pull-right">
        <span class="text-muted">应付总额: ￥
          <%= current_cart.total_price %>
        </span>
        <%= link_to "去结算", checkout_carts_path, method: :post, class:"btn btn-info " %>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>商品信息</th>
          <th>单价</th>
          <th>数量</th>
          <th>小计</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item|  %>
          <tr>
            <td>
              <%= image_tag cart_item.product.avatar.mini.url %>
              <%= cart_item.product.title %>
            </td>
            <td>
              ￥ <%= cart_item.product.price %>
            </td>
            <td>
              <%= cart_item.quantity %>
            </td>
            <td>
              ￥ <%= cart_item.quantity * cart_item.product.price %>
            </td>
            <td>
              <%= link_to "移入收藏夹" %><br>
              <%= link_to "删除" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>