config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :cart_items
  resources :addresses

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
    resources :product_lists
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  namespace :admin do
    resources :orders do
      member do
        post :ship
        post :deliver
        post :return_good
        post :cancel
      end
    end
    resources :products do
      get :publish
      get :unpublish
    end
  end

  namespace :account do
    resources :orders
  end

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @products = Product.all
  end

  def show
    @product = Product.find params[:id]
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new product_params
    if product.save
      redirect_to admin_products_path
      flash.notice = "添加成功"
    else
      redirect_to :new
    end
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    if @product.update product_params
      redirect_to admin_products_path
      flash[:notice] = "更新成功"
    else
      render :edit
    end
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to admin_products_path
    flash[:alert] = "已删除"
  end

  def publish
    product = Product.find params[:product_id]
    product.update(publish: true)
    redirect_back(fallback_location: root_path)
  end

  def unpublish
    product = Product.find params[:product_id]
    product.update(publish: false)
    redirect_back(fallback_location: root_path)
  end

  
  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :repertory, :avatar)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where(publish: true)
  end

  def show
    @product = Product.find params[:id]
  end

  def add_to_cart
    @product = Product.find params[:id]
    if current_cart.products.include?(@product)
      flash[:warning] = "该商品已加入到购物车,不能重复加入"
      redirect_back(fallback_location: root_path)
    else
      current_cart.add_product_to_cart(@product)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for [:admin, @product] do |f| %>
    <%= f.file_field :avatar %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :repertory %>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <%= link_to "添加新商品", new_admin_product_path, class:"btn btn-primary pull-right" %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>编号</th>
          <th>商品图片</th>
          <th>标题</th>
          <th>描述</th>
          <th>价格</th>
          <th>库存</th>
          <th colspan="3">操作</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |p, index| %>
          <tr>
            <td><%= index+1 %></td>

            <td>
              <% if p.avatar.present? %>
                <%= image_tag p.avatar.thumb.url %>
              <% else %>
                <span class="text-warning">暂无图片</span>
              <% end %>
            </td>
            <td><%= link_to p.title, admin_product_path(p) %></td>
            <td><%= p.description %></td>
            <td><%= p.price %></td>
            <td><%= p.repertory %></td>
            <% if p.publish %>
              <td>
                <button type="button" class="btn btn-xs btn-success">已上架</button>
                <%= link_to "下架", admin_product_unpublish_path(p), class:"btn btn-xs btn-danger" %>
              </td>
            <% else %>
              <td>
                <button type="button" class="btn btn-xs btn-warning">已下架</button>
                <%= link_to "上架", admin_product_publish_path(p), class:"btn btn-xs btn-success" %>
              </td>
            <% end %>
            <td><%= link_to "编辑", edit_admin_product_path(p) %></td>
            <td><%= link_to "删除", admin_product_path(p), method: :delete, data:{confirm: "确定要删除吗？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for [:admin, @product] do |f| %>
    <%= f.file_field :avatar %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :repertory %>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <h4>商品详情展示</h4>
    <%= image_tag @product.avatar.thumb.url if @product.avatar.present? %><br>
    <%= @product.title %><br>
    <%= @product.description %><br>
    <%= @product.price %><br>
    <%= @product.repertory %><br>
    <% if @product.publish %>
      <span class="text-warning">已上架</span>
      <%= link_to "下架", admin_product_unpublish_path(@product), class:"btn btn-sm btn-danger" %>
    <% else %>
      <span class="text-muted">已下架</span>
      <%= link_to "上架", admin_product_publish_path(@product), class:"btn btn-sm btn-success" %>
    <% end %>
  </div>
</div>