config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :cart_items
  resources :addresses

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
    resources :product_lists
  end

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  namespace :admin do
    resources :orders do
      member do
        post :ship
        post :deliver
        post :return_good
        post :cancel
      end
    end
    resources :products do
      get :publish
      get :unpublish
    end
  end

  namespace :account do
    resources :orders
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.product.price * cart_item.quantity
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  before_create :generate_token
  belongs_to :address
  has_many :product_lists
  include AASM

  aasm do
    state :order_placed, initial: true #默认状态“已下单”
    state :paid                        #已付款
    state :shipping                    #已发货，运送中…
    state :shipped                     #已收获
    state :order_cancelled             #取消订单
    state :good_returned               #退货

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid ,        to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

  def generate_token
    self.token = SecureRandom.uuid
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  def set_payment_method!(method)
    self.update(payment_method: method)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    user_id = current_user.id
    @address = Address.new address_params
    @address.user_id = user_id
    if @address.save
      redirect_to addresses_path
    else
      render :new
    end
  end

  def edit
    @address = Address.find params[:id]
  end

  def update
    @address = Address.find params[:id]
    if @address.update address_params
      redirect_to addresses_path
    else
      render :edit
    end
  end

  private
  def address_params
    params.require(:address).permit(:phone, :shipping_name, :shipping_address)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def edit
  end

  def update
    cart_item = CartItem.find params[:id]
    quantity = params[:cart_item][:quantity]
    if quantity.to_i <= cart_item.product.repertory.to_i
      cart_item.update cart_item_params
    else
      flash[:alert] = "库存不足，所购商品数量不能超过#{cart_item.product.repertory}"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    cart_item = CartItem.find params[:id]
    cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def checkout
    @order = Order.new
    @addresses = current_user.addresses
  end

  def destroy
    current_cart.cart_items.delete_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only:[:create, :show]

  def create
    @address = Address.find params[:address_id]
    order = Order.new order_params
    order.address_id = @address.id
    order.user_id = current_user.id
    if order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order_id = order.id
        product_list.picture = cart_item.product.avatar.mini.url
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.product_quantity = cart_item.quantity
        product_list.save
      end
      OrderMailer.notify_order_placed(order).deliver!
      redirect_to order_path(order.token)
      flash[:notice] = "已生成订单！"
    end
  end

  def show
    @order = Order.find_by(token: params[:id])
  end

  def pay_with_wechat
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("微信")
    @order.make_payment!
    flash[:notice] = "用微信支付成功"
    redirect_to account_orders_path
  end

  def pay_with_alipay
    @order = Order.find_by_token params[:id]
    @order.set_payment_method!("支付宝宝")
    @order.make_payment!
    flash[:notice] = "用支付宝支付成功"
    redirect_to account_orders_path
  end

  def apply_to_cancel
    @order = Order.find params[:id]
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_back(fallback_location: root_path)
  end

  private
  def order_params
    params.require(:order).permit(:total_money)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where(publish: true)
  end

  def show
    @product = Product.find params[:id]
  end

  def add_to_cart
    @product = Product.find params[:id]
    if current_cart.products.include?(@product)
      flash[:warning] = "该商品已加入到购物车,不能重复加入"
      redirect_back(fallback_location: root_path)
    else
      current_cart.add_product_to_cart(@product)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def product_quantity(product)
    current_cart.cart_items.find_by(product_id: product.id).quantity
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { notice: "success", warning: "warning", alert: "danger" }.freeze

  def user_facing_flashes
    flash.to_hash.slice "alert", "warning", "notice"
  end

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-<%= flash_class(key) %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= value %></strong>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Brand", products_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to carts_path do %>
            购物车
            <i class="fa fa-shopping-cart"></i> <span class="badge badge-danger"><%= current_cart.products.count %></span>
          <% end %>
        </li>
        <% if !user_signed_in? %>
          <li>
            <%= link_to "注册", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "登录", new_user_session_path %>
          </li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "我的订单", account_orders_path %>
              </li>
              <li>
                <%= link_to "管理收货地址", addresses_path(user_id: current_user.id) %>
              </li>
              <li>
                <%= link_to "后台入口", admin_products_path %>
              </li>
              <li>
                <%= link_to "后台订单系统", admin_orders_path %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "退出", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IShopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <%= yield %>
  </body>
</html>